/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.classes.*;
import modelos.interfaces.*;
import persistencia.ManipularArquivo;
/**
 *
 * @author ejmcc
 */
public class TelaPrincipal extends javax.swing.JFrame {

  IServicos professores = null;
  /**
   * Creates new form TelaPrincipal
   */
  public TelaPrincipal() {
    initComponents();
    this.setLocationRelativeTo(null);
    ManipularArquivo dados = new ManipularArquivo("./src/arquivodedados/DocentesEscola.csv");
    try {
      professores = dados.obterListaProfessores();
      //Incluir
      //mostrarNaGrid(professores.listagemDeProfessores());
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane,"ERRO CRIACAO DO CONJUNTO");
    }
    
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jTextFieldNome = new javax.swing.JTextField();
    jTextFieldMatricula = new javax.swing.JTextField();
    jTextFieldEscola = new javax.swing.JTextField();
    jComboBoxTitulacao = new javax.swing.JComboBox<>();
    jComboBoxTipoDeContrato = new javax.swing.JComboBox<>();
    jPanel3 = new javax.swing.JPanel();
    jButtonIncluir = new javax.swing.JButton();
    jButtonExcluir = new javax.swing.JButton();
    jButtonAlterar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTableSaida = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(0, 102, 153));
    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 3));

    jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("SISTEMA DE CONTROLE DOS PROFESSORES");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(308, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addGap(286, 286, 286))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addComponent(jLabel1)
        .addContainerGap(45, Short.MAX_VALUE))
    );

    jPanel2.setBackground(new java.awt.Color(102, 255, 204));
    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "DADOS DO PREOFESSOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 3, 18))); // NOI18N

    jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
    jLabel2.setText("MATRICULA");

    jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
    jLabel3.setText("NOME");

    jLabel4.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
    jLabel4.setText("ESCOLA");

    jLabel5.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
    jLabel5.setText("TITULAÇÃO");

    jLabel6.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
    jLabel6.setText("TIPO DO CONTRATO");

    jTextFieldNome.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N

    jTextFieldMatricula.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N

    jTextFieldEscola.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N

    jComboBoxTitulacao.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
    jComboBoxTitulacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MESTRE(A)", "DOUTOR(A)", "ETC" }));

    jComboBoxTipoDeContrato.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
    jComboBoxTipoDeContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "HORISTA" }));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel6)
            .addGap(26, 26, 26)
            .addComponent(jComboBoxTipoDeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextFieldEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel5)
            .addGap(18, 18, 18)
            .addComponent(jComboBoxTitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(19, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3)
          .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jTextFieldEscola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5)
          .addComponent(jComboBoxTitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(jComboBoxTipoDeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(26, 26, 26))
    );

    jPanel3.setBackground(new java.awt.Color(255, 204, 0));
    jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

    jButtonIncluir.setText("INCLUIR");
    jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonIncluirActionPerformed(evt);
      }
    });

    jButtonExcluir.setText("EXCLUIR");
    jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonExcluirActionPerformed(evt);
      }
    });

    jButtonAlterar.setText("ALTERAR");
    jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonAlterarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(68, 68, 68)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButtonIncluir)
          .addComponent(jButtonExcluir)
          .addComponent(jButtonAlterar))
        .addContainerGap(67, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(jButtonIncluir)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
        .addComponent(jButtonExcluir)
        .addGap(33, 33, 33)
        .addComponent(jButtonAlterar)
        .addGap(38, 38, 38))
    );

    jTableSaida.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    jTableSaida.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "MATRICULA", "NOME", "ESCOLA", "TITULAÇÃO", "CONTRATO"
      }
    ));
    jScrollPane1.setViewportView(jTableSaida);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 15, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void mostrarNaGrid(Professor[] dadosDosProfessores) throws Exception {
    try {
      DefaultTableModel model = (DefaultTableModel) jTableSaida.getModel();
      model.setNumRows(0); // Limpa a tabela antes de atualizar

      for (Professor objetoProfessor : dadosDosProfessores) {
        if (objetoProfessor != null) { // Verifica se o objeto não é nulo
          model.addRow(new Object[]{
                  objetoProfessor.getMatricula(),
                  objetoProfessor.getNome(),
                  objetoProfessor.getEscola(),
                  objetoProfessor.getTitulacao(),
                  objetoProfessor.getTipoContrato()
          });
        }
      }
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro.getMessage());
    }
  }


  private void limparCampos() {
    jTextFieldMatricula.setText("");
    jTextFieldNome.setText("");
    jTextFieldEscola.setText("");
    jComboBoxTitulacao.setSelectedIndex(0);
    jComboBoxTipoDeContrato.setSelectedIndex(0);
  }

  private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
    try {
      int matricula = Integer.parseInt(jTextFieldMatricula.getText());
      String nome = jTextFieldNome.getText();
      String escola = jTextFieldEscola.getText();
      String titulacao = (String) jComboBoxTitulacao.getSelectedItem();
      String contrato = (String) jComboBoxTipoDeContrato.getSelectedItem();

      Professor objetoProfessor = new Professor(matricula, nome, escola, titulacao, contrato);
      professores.incluir(objetoProfessor);

      // Atualiza a tabela após incluir o novo professor
      mostrarNaGrid(professores.listagemDeProfessores());

      // Limpar campos após inclusão
      limparCampos();

    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro.getMessage());
    }
  }//GEN-LAST:event_jButtonIncluirActionPerformed


  private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
    try {
      int matricula = Integer.parseInt(JOptionPane.showInputDialog("Digite a matrícula do professor a ser excluído:"));
      professores.excluir(matricula);

      // Atualiza a tabela após excluir o professor
      mostrarNaGrid(professores.listagemDeProfessores());
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro.getMessage());
    }
  }//GEN-LAST:event_jButtonExcluirActionPerformed

  private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
    try {
      int matricula = Integer.parseInt(jTextFieldMatricula.getText());
      String nome = jTextFieldNome.getText();
      String escola = jTextFieldEscola.getText();
      String titulacao = (String) jComboBoxTitulacao.getSelectedItem();
      String contrato = (String) jComboBoxTipoDeContrato.getSelectedItem();

      Professor objetoProfessor = new Professor(matricula, nome, escola, titulacao, contrato);
      professores.alterar(objetoProfessor);

      // Atualiza a tabela após alterar o professor
      mostrarNaGrid(professores.listagemDeProfessores());
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro.getMessage());
    }
  }//GEN-LAST:event_jButtonAlterarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TelaPrincipal().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAlterar;
  private javax.swing.JButton jButtonExcluir;
  private javax.swing.JButton jButtonIncluir;
  private javax.swing.JComboBox<String> jComboBoxTipoDeContrato;
  private javax.swing.JComboBox<String> jComboBoxTitulacao;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTableSaida;
  private javax.swing.JTextField jTextFieldEscola;
  private javax.swing.JTextField jTextFieldMatricula;
  private javax.swing.JTextField jTextFieldNome;
  // End of variables declaration//GEN-END:variables
}
